In [1]:
import numpy as np

In [2]:
listx = [11, 22, 44, 16]

listy = [[10, 20, 30], 
        [90, 80, 70], 
        [50, 60, 40]]

In [3]:
na = np.array(listx)

In [4]:
print(type(listx))

<class 'list'>


In [5]:
print(type(na))

<class 'numpy.ndarray'>


In [6]:
print(na)

[11 22 44 16]


In [7]:
print(listx)

[11, 22, 44, 16]


In [8]:
print(na * 3)

[ 33  66 132  48]


In [9]:
print(na)

[11 22 44 16]


In [10]:
nb = np.array(listy)

In [11]:
print(nb)

[[10 20 30]
 [90 80 70]
 [50 60 40]]


In [12]:
print(nb + 5)

[[15 25 35]
 [95 85 75]
 [55 65 45]]


In [13]:
na.ndim

1

In [14]:
nb.ndim

2

In [15]:
nc = np.array([[11, 22, 33], [34, 67, 90], [87, 64, 31], [29, 52, 85]])

In [16]:
print(nc)

[[11 22 33]
 [34 67 90]
 [87 64 31]
 [29 52 85]]


In [17]:
nc.ndim

2

In [18]:
nc.shape

(4, 3)

In [19]:
nc.size

12

In [20]:
nc[1, 1]

67

In [21]:
nc[2, -2]

64

In [22]:
nc[2, 2]

31

In [23]:
nc.all()

True

In [24]:
nc.any()

True

In [25]:
nc.mean()

50.416666666666664

In [26]:
nc.shape

(4, 3)

In [28]:
print(nc.reshape(2, 6))

[[11 22 33 34 67 90]
 [87 64 31 29 52 85]]


In [29]:
print(nc)

[[11 22 33]
 [34 67 90]
 [87 64 31]
 [29 52 85]]


In [30]:
print(nc.reshape(6, -1))

[[11 22]
 [33 34]
 [67 90]
 [87 64]
 [31 29]
 [52 85]]


In [31]:
print(nc.reshape(5, -1))

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [33]:
nd = nc.reshape(3, 2, 2)

In [34]:
print(nd)

[[[11 22]
  [33 34]]

 [[67 90]
  [87 64]]

 [[31 29]
  [52 85]]]


In [36]:
print(nd[0])

[[11 22]
 [33 34]]


In [37]:
print(nd[0][0])

[11 22]


In [38]:
print(nd[0][0][1])

22


In [39]:
print(nd)

[[[11 22]
  [33 34]]

 [[67 90]
  [87 64]]

 [[31 29]
  [52 85]]]


In [40]:
print(nd[1][1][0])

87


In [44]:
ne = np.array([[[11, 22, 33, 44], [34, 67, 90, 12]], 
               [[87, 64, 31, 45], [29, 52, 85, 10]]])

In [45]:
print(ne)

[[[11 22 33 44]
  [34 67 90 12]]

 [[87 64 31 45]
  [29 52 85 10]]]


In [46]:
ne.ndim

3

In [47]:
ne.shape

(2, 2, 4)

In [48]:
print(ne[0])

[[11 22 33 44]
 [34 67 90 12]]


In [49]:
print(ne[1])

[[87 64 31 45]
 [29 52 85 10]]


In [50]:
print(ne[1][0])

[87 64 31 45]


In [51]:
print(ne[1][0][2])

31


In [53]:
print(ne[1][1][2]) 

85


In [54]:
print(ne)

[[[11 22 33 44]
  [34 67 90 12]]

 [[87 64 31 45]
  [29 52 85 10]]]


In [55]:
print(np.swapaxes(ne, 1, 2))

[[[11 34]
  [22 67]
  [33 90]
  [44 12]]

 [[87 29]
  [64 52]
  [31 85]
  [45 10]]]


### axis

In [58]:
print(nd)

[[[11 22]
  [33 34]]

 [[67 90]
  [87 64]]

 [[31 29]
  [52 85]]]


In [59]:
print(ne)

[[[11 22 33 44]
  [34 67 90 12]]

 [[87 64 31 45]
  [29 52 85 10]]]


In [60]:
print(nc)

[[11 22 33]
 [34 67 90]
 [87 64 31]
 [29 52 85]]


In [61]:
# axis 0 = vertical, axis 1 = horizontal

In [62]:
nc.max()

90

In [63]:
nc.max(axis=0)

array([87, 67, 90])

In [64]:
nc.max(axis =1 )     # 33, 90, 87, 85

array([33, 90, 87, 85])

In [65]:
print(nd)

[[[11 22]
  [33 34]]

 [[67 90]
  [87 64]]

 [[31 29]
  [52 85]]]


In [66]:
nd.max(axis = 0)

array([[67, 90],
       [87, 85]])

In [67]:
nd.max(axis = 1)

array([[33, 34],
       [87, 90],
       [52, 85]])

In [68]:
nd.max(axis = 2)

array([[22, 34],
       [90, 87],
       [31, 85]])

In [69]:
print(nd)

[[[11 22]
  [33 34]]

 [[67 90]
  [87 64]]

 [[31 29]
  [52 85]]]


In [71]:
print(np.swapaxes(nd, 0, 1))

[[[11 22]
  [67 90]
  [31 29]]

 [[33 34]
  [87 64]
  [52 85]]]


In [72]:
lista = ["natalie", "female", "jeusalem", "israel"]
listb = ["bruce", "male", "dortmund", "germany"]
listc = ["emma", "female", "paris", 'france']
listd = ["keanu", "male", "beirut", "israel"]

In [84]:
nf =np.array([[['natalie', 'female'],['jeusalem' ,'israel']], 
          [['bruce', 'male' ], ['dortmund' ,'germany']], 
         [['emma', 'female'], ['paris', 'france']]])

In [85]:
print(nf)

[[['natalie' 'female']
  ['jeusalem' 'israel']]

 [['bruce' 'male']
  ['dortmund' 'germany']]

 [['emma' 'female']
  ['paris' 'france']]]


In [99]:
print(nf.sort(axis = 0))

None
